[build]
  command = "npx update-browserslist-db@latest && npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200